# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_users_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_rate',
            field=models.IntegerField(default=0),
        ),
    ]
