# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_post_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 18, 42, 52, 533417)),
        ),
    ]
