# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
